LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := viper4aFX
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE_CLASS := APPS
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_SRC_FILES := viper4aFX/viper4aFX.apk
LOCAL_VENDOR_MODULE := true
LOCAL_OVERRIDES_PACKAGES := AudioFX
include $(BUILD_PREBUILT)
